import { LocalizedStrings } from "react-native-easy-localization-and-rtl";

const i18n = new LocalizedStrings({
    en: {
      foodApp:'Food Delivery App',
      signIn:'Sign In',
      signUp:'Sign Up',
      email:'Email address',
      password:'Password',
      confirmPassword:'Confirm Password',
      forgotPassword:'Forgot Password?',
      clickHere:'Click here',
      dontHaveAccount:"Don't have an account?",
      userName:'User Name',
      firstName:'First Name',
      lastName:'Last Name',
      errorTitle:'Error Occurred',
      enterUser:'Please enter username',
      enterFirstName:'Please enter first name',
      enterLastName:'Please enter last name',
      enterEmail:'Please enter email address',
      enterPassword:'Please enter password',
      passwordDidNotMatch:'Passwords did not match',
      alreadyHaveAccount:'Already have an account?',
      deliveryAddresses : 'Delivery Addresses',
      myOrders: 'My Orders',
      favourites:'Favourites',
      callHelpCenter:'Call Help Center',
      changeLanguage:'Change Language',
      logout:"Logout",
      findAwesomeDealsNearYou : 'Find awesome deals near you',
      weNeedToAccessYourLocation : 'We need to access your location to give you a better experience',
      allowAccessToMyLocation : 'Allow access to my location',
      selectAnotherLocation : 'Select another location',
      home : 'Home',
      email: 'Email',
      phone : 'Phone',
      changePassword: 'Change Password',
      done:'Done',
      currentPassword:'Current Password',
      newPassword: 'New Password',
      YourCartIsEmpty: 'Your cart is empty',
      LooksLikeYouHaventAddedAnyItemsToYourCartYet: "Looks like you haven't added any items to your cart yet.",
      categories: 'Categories',
      availableCtegories: 'Available Categories',
      editProfile: 'Edit Profile',
      noAddressFound:'No address found',
      addNewAddress: 'Add new address',
      myAddresses:'My Addresses',
      address:'Address',
      city:'City',
      state:'State',
      country:'Country',
      deliveryInstructions: 'Delivery instructions',
      work: 'Work',
      other: 'Other',
      addAddress:'Add Address',
      editAddress:'Edit Address',
      paymentDetails:'Payment Details',
      enterNameOnCard:'Enter name on card',
      entercardNumber:'Enter card number',
      noOrdersFound:'No orders found',
      myFavourites:'My Favourites',
      allRestaurant:"All Restaurants",
      seemsLikeThereAreNoRestaurantAvailableNearYourLocation: "Seems like there are no restaurants available near your location",
      noRestaurantFound:"No Restaurant Found",
      currentlyRestaurantsFromThisCategoryAreUnavailable :'Currently Restaurants from this category are unavailable, but we will soon add them for you. Please Try again later.',
      searchForRestaurantsAndDishes :"Search for restaurants and dishes",
      enterCoupon: 'Enter Coupon',
      enterCodeHere:'Enter code here',
      apply:'Apply',
      outOfReach:'Out of reach',
      confirmLocation:'Confirm location',
      price:'Price',
      addMoreFood:'Add more food',
      addNotes:"Add Notes",
      enterDeliveryInstructions:'Enter delivery instructions',
      subtotal:"Subtotal",
      totalDiscount:'Total Discount',
      deliveryCost:"Delivery Cost",
      free:"Free",
      totalAmount:"Total amount",
      checkout:'Checkout',
      somethingWentWrong:'Sorry, something went wrong',
      tryAgain:'Try again',
      rate:'Rate',
      orderStatus:'Order Status',
      estimatedDeliveryTime:"Estimated Time",
      cancelOrder:'Cancel Order',
      enterAddress:'Please Enter Full Address',
      enterCity:'Please Enter City',
      enterState:'Please Enter State',
      enterCountry:'Please Enter Country',
      requestSuccessfull:'Request Successfull',
      enterCurrentPassword:'Please enter current password',
      enterNewPassword:'Please enter new password',
      enterPhone:'Please enter phone number',
      enterFullName:'Please enter full name',
      fullName:'Full Name',
      youHaveNotPlacedOrder:"You haven't placed any orders yet",
      viewYourCart:'View Your Cart',
      noReviewsAvailiable:"No Reviews available",
      reviews:'Reviews',
      writeReview:'Write a review',
      submit:'Submit',
      restaurantDoesntDeliver:"Restaurant doesn't deliver to your location",
      noteToRider:'Note to rider: ',
      items:"Items :",
      total:'Total :',
      emptyCart:"Empty cart?",
      youHaveItemsInCart: "You already have items in your cart. Do you want to discard them?",
      discardCart:"Discard Cart",
      searchForLocation:"Search for your location...",
      deliveryAddress:'Delivery Address',
      change:'Change',
      doYouHaveVoucher:"Do you have a voucher?",
      removeVoucher:'Remove Voucher',
      delivery:'Delivery',
      pickup:'Pickup',
      paymentMethod:"Payment Method",
      cashOnDelivery:'Cash on Delivery',
      onlinePayment:"Online Payment",
      coupon:'Coupon',
      summary:'Summary',
      couponDiscount:'Coupon Discount',
      orderPlacedAt:'Order Placed at : ',
      discount:'Discount',
      deliveryFee:"Delivery Fee",
      basketTotal:"Basket Total (inc. tax)",
      callRider:'Call Rider',
      currentOrders:'Current Orders',
      thankyouForYourOrder:'Thank you for your order',
      youCanTrackOrder:'You can track the order in "Orders" section',
      trackMyOrder: 'Track My Order',
      orderSomethingElse:'Order something else',
      pleaseWaitWhileWeConfirm:"Please wait while we confirm your order",
      yourRider:'Your Rider',
      orderConfirmed:"Order Confirmed",
      preparingFood:"Preparing Your Food",
      orderIsReadyAtRestaurant:"Order is ready at the restaurant",
      riderIsPicking:"Rider is picking up your order",
      riderIsNearby:"Rider is nearby your place",
      cart:'Cart',
      profile:'Profile',
      search:'Search',
      deliverTo:'Deliver to',
      currentLocation:'Current location',
      selectedLocation:'Selected location',
      addNewAddress:'Add new address',




    },
    
    it:{
      foodApp:'App di consegna cibo',
      signIn:'Registrati',
      signUp:'Iscriviti',
      email:'Indirizzo email',
      password:"Parola d'ordine",
      confirmPassword:'Conferma password',
      forgotPassword:'Ha dimenticato la password?',
      clickHere:'Clicca qui',
      dontHaveAccount:'Non hai un account?',
      userName:'Nome utente',
      firstName:'Nome di battesimo',
      lastName:'Cognome',
      errorTitle:'Errore',
      enterUser:'Per favore, inserisci il nome utente',
      enterFirstName:'Per favore inserisci il nome',
      enterLastName:'Per favore inserisci il cognome',
      enterEmail:"Si prega di inserire l'indirizzo e-mail",
      enterPassword:'Per favore, inserisci la password',
      passwordDidNotMatch:'Le password non coincidono',
      alreadyHaveAccount:'Hai già un account?',
      deliveryAddresses:'Indirizzi di consegna',
      myOrders: 'I miei ordini',
      favourites:'Preferite',
      callHelpCenter:'Chiama il Centro assistenza',
      changeLanguage:'Cambia lingua',
      logout:'disconnettersi',
      findAwesomeDealsNearYou : 'Trova offerte fantastiche vicino a te',
      weNeedToAccessYourLocation : "Dobbiamo accedere alla tua posizione per offrirti un'esperienza migliore",
      allowAccessToMyLocation : "consentire l'accesso alla mia posizione",
      selectAnotherLocation : "Seleziona un'altra posizione",
      home: 'Casa',
      email: 'E-mail',
      phone : 'Telefono',
      changePassword: 'Cambia la password',
      done:'Fatto',
      currentPassword:'Password attuale',
      newPassword: 'Nuova password',
      YourCartIsEmpty: "Il tuo carrello è vuoto",
      LooksLikeYouHaventAddedAnyItemsToYourCartYet: 'Sembra che tu non abbia ancora aggiunto alcun articolo al tuo carrello.',
      categories: 'Categorie',
      availableCtegories: 'Categorie Disponibili',
      editProfile: 'Modifica Profilo',
      noAddressFound:'Nessun indirizzo trovato',
      addNewAddress: 'Aggiungi un nuovo indirizzo',
      myAddresses:'I miei indirizzi',
      address:'Indirizzo',
      city:'Città',
      state:'Stato',
      country:'Nazione',
      deliveryInstructions: 'Istruzioni per la consegna',
      work: 'Lavoro',
      other: 'Altra',
      addAddress:'Aggiungi indirizzo',
      editAddress:'Modifica indirizzo',
      paymentDetails:'Dettagli di pagamento',
      enterNameOnCard:'Inserisci il nome sulla carta',
      entercardNumber:'Inserisci il numero della carta',
      noOrdersFound:'Nessun ordine trovato',
      myFavourites:'I miei preferiti',
      allRestaurant:"Tutti i ristoranti",
      seemsLikeThereAreNoRestaurantAvailableNearYourLocation: "Sembra che non ci siano ristoranti disponibili vicino alla tua posizione",
      noRestaurantFound:"Nessun ristorante trovato",
      currentlyRestaurantsFromThisCategoryAreUnavailable :'Attualmente i ristoranti di questa categoria non sono disponibili, ma presto li aggiungeremo per te. Per favore riprova più tardi.',
      searchForRestaurantsAndDishes :"Cerca ristoranti e piatti",
      enterCoupon: 'Inserisci Coupon',
      enterCodeHere:'Inserire il codice qui',
      apply:'Applicare',
      outOfReach:'Fuori portata',
      confirmLocation:'Conferma posizione',
      price:'Prezzo',
      addMoreFood:'Aggiungi altro cibo',
      addNotes:"Aggiungi Note",
      enterDeliveryInstructions:'Inserisci le istruzioni di consegna',
      subtotal:"totale parziale",
      totalDiscount:'Sconto totale',
      deliveryCost:"Costo di consegna",
      free:"Gratuito",
      totalAmount:"Importo totale",
      checkout:'Check-out',
      somethingWentWrong:'Scusa, qualcosa è andato storto',
      tryAgain:'Riprova',
      rate:'Vota',
      orderStatus:"Lo stato dell'ordine",
      estimatedDeliveryTime:"Tempo stimato",
      cancelOrder:'Annulla Ordine',
      enterAddress:"Si prega di inserire l'indirizzo completo",
      enterCity:'Per favore, inserisci la città',
      enterState:'Per favore, inserisci lo stato',
      enterCountry:'Per favore, inserisci il Paese',
      requestSuccessfull:'Richiesta riuscita',
      enterCurrentPassword:'Inserisci la password corrente',
      enterNewPassword:'Inserisci una nuova password',
      enterPhone:'Inserisci il numero di telefono',
      enterFullName:'Per favore, inserisci il nome completo',
      fullName:'Nome e cognome',
      youHaveNotPlacedOrder:"Non hai ancora effettuato alcun ordine",
      viewYourCart:'Visualizza il tuo carrello',
      noReviewsAvailiable:"Nessuna recensione disponibile",
      reviews:'Recensioni',
      writeReview:'Scrivere una recensione',
      submit:'Invia',
      restaurantDoesntDeliver:"Il ristorante non consegna alla tua posizione",
      noteToRider:'Nota per il ciclista : ',
      items:"Elementi :",
      total:'Totale :',
      emptyCart:"Carrello vuoto?",
      youHaveItemsInCart: "Hai già degli articoli nel carrello. Vuoi scartarli?",
      discardCart:"Elimina carrello",
      searchForLocation:"Cerca la tua posizione...",
      deliveryAddress:'Indirizzo di consegna',
      change:'Modificare',
      doYouHaveVoucher:"Hai un buono?",
      removeVoucher:'Rimuovi voucher',
      delivery:'Consegna',
      pickup:'Raccogliere',
      paymentMethod:"Metodo di pagamento",
      cashOnDelivery:'Pagamento alla consegna',
      onlinePayment:"Pagamento online",
      coupon:'Buona',
      summary:'Sommario',
      couponDiscount:'Sconto coupon',
      orderPlacedAt:'Ordine effettuato a : ',
      discount:'Sconto',
      deliveryFee:"Tassa di consegna",
      basketTotal:"Totale paniere (tasse incluse)",
      callRider:'Chiama Rider',
      currentOrders:'Ordini correnti',

      thankyouForYourOrder:'Grazie per il vostro ordine',
      youCanTrackOrder:"Puoi tracciare l'ordine nella sezione Ordini",
      trackMyOrder: 'Traccia il mio ordine',
      orderSomethingElse:"Ordina qualcos'altro",
      pleaseWaitWhileWeConfirm:"Attendi mentre confermiamo il tuo ordine",
      yourRider:'Il tuo cavaliere',
      orderConfirmed:"Ordine Confermato",
      preparingFood:"Preparare il tuo cibo",
      orderIsReadyAtRestaurant:"L'ordine è pronto al ristorante",
      riderIsPicking:"Rider sta ritirando il tuo ordine",
      riderIsNearby:"Il cavaliere è vicino a casa tua",
      cart:'Carrello',
      profile:'Profilo',
      search:'Ricerca',
      deliverTo:'Spedire a',
      currentLocation:'Posizione attuale',
      selectedLocation:'Posizione selezionata',
      addNewAddress:'Aggiungi un nuovo indirizzo',




      


    }
  });

  export default i18n;